workspace(name = "bazel_ls_demo_project")

load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

http_archive(
    name = "bazel_skylib",
    type = "tar.gz",
    sha256 = "bc283cdfcd526a52c3201279cda4bc298652efa898b10b4db0837dc51652756f",
    urls = [
        "https://github.com/bazelbuild/bazel-skylib/releases/download/1.7.1/bazel-skylib-1.7.1.tar.gz",
    ],
)

# check minimum Bazel version
load("@bazel_skylib//lib:versions.bzl", "versions")

versions.check(minimum_bazel_version = "5.0.0")

http_archive(
    name = "salesforce_rules_mybuilder",
    sha256 = "1eb96edc0dd22bab71386a8ee84a8636b1b9acea6db64f8ceed67903fa140dbf",
    strip_prefix = "bazel-java-builder-template-2f4d0574885c6455a9c6f1fdf20b7f64225a946a",
    url = "https://github.com/salesforce/bazel-java-builder-template/archive/2f4d0574885c6455a9c6f1fdf20b7f64225a946a.zip",
)

load("@salesforce_rules_mybuilder//mybuilder:repositories.bzl", "rules_mybuilder_dependencies", "rules_mybuilder_toolchains")

rules_mybuilder_dependencies()

rules_mybuilder_toolchains()

# Maven dependencies
load("//third_party/maven:dependencies.bzl", "maven_dependencies")

maven_dependencies()
